### ISSUE TITLE
Title bar not hiding in GNOME

### ISSUE THREAD

**Issue by SillyQuestionAlt** [morpheusthewhite/spicetify-themes#109]
I should of been more specific. I have CSS to hide title bars for every window in GNOME. It for some reason does not work for this specific collection of spicetiy themes. I was just simply asking if this is some known issue, or am I going to be given a non-answer and have my thread closed immediately again.

**Comment by morpheusthewhite** [comment]
Sorry, I didn't want to be rude, but from your previous informations I wasn't able to understand much (you could have reopened that issue again instead of this new one btw): all I read was like "I want to hide the title bar in Spotify, how can I do it?"

However I'm pretty confident that this problem is not related to the themes but to your Desktop Environment (I cannot directly test it) since the theme apply just to the window content while the title bar are handled by the OS.

**Comment by morpheusthewhite** [comment]
If you look at [bittersweet](https://camo.githubusercontent.com/32f9ceeab78ddc65f7075ffe74d28647e7c0490c/68747470733a2f2f692e696d6775722e636f6d2f3058426f6a76382e6a7067) it should be pretty clear where the theme end and when the Desktop environment starts
