### ISSUE TITLE
Dribbblish: Sidebar theming bug/inconsistency 

### ISSUE THREAD

**Issue by Fahrenheit** [morpheusthewhite/spicetify-themes#136]
<img width="76" alt="Screen Shot 197" src="https://user-images.githubusercontent.com/33299777/87805431-4c6f6200-c823-11ea-8fe0-c22bd7dae774.png">

As Spotify just added folders recently, I noticed the folder name doesn't theme and stays black which can clash with the background color. The text can be unreadable or gets cut off, but that's just a result of the sidebar size I assume. One other minor thing was when I turned on local files it seemed to not theme that icon until I restarted Spotify. Just thought I'd point that out.

**Comment by khanhas** [comment]
1. Folder name cutoff is intentional since Spotify does not allow user to set picture for playlist folder. So I just put their first 3 letters, if you want folders icons to match with the rest, set them to emojis I guess. I saw someone did it and they look okay.
2. Dribbblish script changes apps text to icon only once on Spotify startup. So you probably don't turn on, turn off Local Files on daily basis just to see the theme break, do you?

**Comment by Fahrenheit** [comment]
>     1. Folder name cutoff is intentional. Spotify does not allow user to set picture for playlist folder, so I just put their first 3 letters. If you want folders icons to match with the rest, set them to emojis I guess. I saw someone did it and they look okay.
> 
>     2. Dribbblish script changes apps text to icon only once on Spotify startup. So you probably don't turn on, turn off Local Files on daily basis just to see the theme break, do you?

Thanks for the quick reply. I'll try that emoji idea as it's a pretty good idea. Also yeah I obviously don't, but wasn't sure if the theming with the local files could possibly be an issue that would reappear.
