### ISSUE TITLE
Purple theme isnt applying

### ISSUE THREAD

**Issue by pavanmannem** [morpheusthewhite/spicetify-themes#139]

**Comment by morpheusthewhite** [comment]
I cannot help if you don't provide any information.

Please make sure to properly follow instructions.

**Comment by tuanbinhtran** [comment]
It's most likely your spicetify-cli is not up to date. 
spicetify-cli supports custom color keys since v0.9.9. So, if you downloaded the cli for example on chocolatey, your cli is not updated(which was in my case)

Download the new cli from here: [https://github.com/khanhas/spicetify-cli/releases](https://github.com/khanhas/spicetify-cli/releases)
And lastly, just reapply the theme.
