### ISSUE TITLE
SpotifyNoControl.exe taskbar icon does not have same appID with Spotify (Dribbblish)

### ISSUE THREAD

**Issue by ragnarcb** [morpheusthewhite/spicetify-themes#233]
I don't know if you consider this a bug but, I create a shortcut for SpotifyNoControl.exe, give it the Spotify icon and pin it to taskbar. Then, I run it, Spotify opens but in a different, second taskbar icon. This reduces the usability of SpotifyNoControl.exe. I believe it can be done like described in the first answer here: https://stackoverflow.com/questions/25393875/combine-two-applications-into-one-icon-on-taskbar, that would require knowledge of Spotify's appID though. Also, when I run NoControl.exe, there is a terminal window opened and stays there for 3-4 seconds. Maybe developers can easily make this terminal window happen in background.

**Comment by morpheusthewhite** [comment]
@khanhas

**Comment by khanhas** [comment]
Sorry. I have zero idea how to do it.
Here its complete source code and project files to build if anyone wants to have a cracks at it:
[Project2.zip](https://github.com/morpheusthewhite/spicetify-themes/files/5813046/Project2.zip)

**Comment by bernawastaken** [comment]
I found some information on how to possibly do it. Running `get-StartApps` on powershell prints the AppID of all the apps in the system. It's more than likely that AppIDs vary from device to device and on another Windows 10 machine the command gave me the installation folder of certain apps rather than the AppID. On the code side of things I found [this](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-setcurrentprocessexplicitappusermodelid) microsoft docs page with info on how to set the AppID. I'll see if I can manage to make something work out but C++ is not a language I'm too familiar with.

**Comment by morpheusthewhite** [comment]
That would be great

**Comment by JulienMaille** [comment]
On my computer `get-StartApps` returns the path to Spotify. I've set this using `SetCurrentProcessExplicitAppUserModelID` but I still have 2 separate icons in the toolbar

**Comment by JulienMaille** [comment]
I found a way to do this using https://code.google.com/archive/p/win7appid/
Use it to give the same appID to both you Spotify shortcut and your SpotifyNoControl shortcut.
