### ISSUE TITLE
Sleek has a red playing animation despite me not setting it.

### ISSUE THREAD

**Issue by StarrKiss** [morpheusthewhite/spicetify-themes#420]
I am usign the sleek theme here with a custom color scheme I wrote that is as follows:

[Scraper]
; custom to fit with wallpaper
text               = 3fb9a2
subtext            = 95b9b2
button-text        = 001b30
main               = 001b30
sidebar            = 091f37
player             = 0a223d
card               = 0a223d
shadow             = 7feeff
selected-row       = 0c2846
sub-button         = 359b87
button             = 3fb9a2
button-active      = 44c8ae
button-disabled    = 353535
tab-active         = 303030
notification       = 0a223d
notification-error = 0a223d
playback-bar       = 3fb9a2
misc               = FFFFFF

However, despite this, the color of the playing animation to the left of the song is dark red, with hex code #8d0000, that appears nowhere in my color scheme, or, indeed, in the user.css which I already slightly edited to make the shadows bigger.
![image](https://user-images.githubusercontent.com/13007697/123442662-bb5c4b80-d59a-11eb-8a3a-228a8db04c3a.png)

This seems like an issue with Sleek.

**Comment by morpheusthewhite** [comment]
Use the inspector to detect the element associated with it and check if you modified something that applies to it

**Comment by CharlieS1103** [comment]
@StarrKiss Hello, I work on sleek theme quite a bit, I'm going to look into changing the red marker for each theme soon, I already have a method for doing it, just need to work on it a bit lol.

**Comment by CharlieS1103** [comment]
@StarrKiss Just to extend on that, the playing bar using hue and degrees and such, don't worry about it for now and wait till the next sleek theme release.

**Comment by harbassan** [comment]
Oh damn, completely forgot to change that colour on each theme. The reason you can't change it is because it is a gif, and to apply certain colours to that GIF, filters have to be used. Unless @CharlieS1103 has already done it, I'll try and update that. Or if you want to do this yourself, use this [css filters website](https://codepen.io/sosuke/pen/Pjoqqp) and then apply the result into the css, under the .main-trackList-playingIcon selector.

**Comment by CharlieS1103** [comment]
@harbassan I'm figuring out a way to change it between the different color schemes using media-queries, it'll be messy but it might work.

**Comment by CharlieS1103** [comment]
So I came in with a lot of ideas, worked on it for a few hours, and one by one each of those ideas got squashed. If you have any clue on how to change this per each theme I would love to hear you thoughts. @harbassan. I tried a few things, declaring variables and editing their values to be the degree I want after calculations are done, in the color.ini and then using calc to set the said variables to desired value. However that attempt didn't work because hue-rotate requires a degree unit, extracting the R and G values out of something might work, but I don't see how that's possible in css, if all goes wrong I'll try writing a javascript extension for it, or perhaps remove the gif entirely(or just setting it to a milder tone, which I have done for now.).

**Comment by harbassan** [comment]
Yeah the only thing I can think of is using a JavaScript solution to convert the hex value into a CSS filter, which there are already a few of luckily.

**Comment by CharlieS1103** [comment]
@harbassan Check out v 2.5 of spicetify, is there anything involving the new asset management we could use?

**Comment by CharlieS1103** [comment]
@harbassan Check out https://github.com/morpheusthewhite/spicetify-themes/discussions/435

**Comment by CharlieS1103** [comment]
@StarrKiss Mind closing this issue as it's resolved(most themes should update it soon.)
