### ISSUE TITLE
Dribbblish not working after Spotify update

### ISSUE THREAD

**Issue by Hu1buerger** [morpheusthewhite/spicetify-themes#453]
When configuring spicetify to use the Dribbblish Theme with base theme the theme doesn't load. 

**To Reproduce**
1. Install spicetify 
2. Install Spotify 
3. Confirm that spicetify works aka DefaultTheme gets displayed.
4. Run the commands from the readme for Dribbblish
5. Restart Spotify 

**Expected behavior**
Dribbblish theme gets loaded and displayed.

**What actually happens**
Spotify uses normal SpotifyTheme as if not using spicetify at all.

**Logs**
```console
dribbblish.js:2 Uncaught TypeError: Cannot read property 'style' of null
    at dribbblish.js:2
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
xpui.js:1 AllboardingAPINoOp.shouldShowOnLoad
2
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
xpui.js:1 No container found for fullscreen video!
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2364353)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2366635)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:1799495
    at ka (https://xpui.app.spotify.com/vendor~xpui.js:29:2647517)
    at Ps (https://xpui.app.spotify.com/vendor~xpui.js:29:2671369)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2873919)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2617025)
    at Cs (https://xpui.app.spotify.com/vendor~xpui.js:29:2671148)
    at ws (https://xpui.app.spotify.com/vendor~xpui.js:29:2655919)
    at ys (https://xpui.app.spotify.com/vendor~xpui.js:29:2654841)
vendor~xpui.js:1 [transport.transport] Auth header setting awaiting authentication.
4
vendor~xpui.js:1 [transport.transport] Auth header set after authentication.
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/773.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load SourceMap: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

when commenting line dribbblish.js:2 out, one additional exception gets thrown.

```console
Uncaught TypeError: Cannot read property 'username' of undefined
    at dribbblish.js:47
```

Logs will follow
**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version 1.1.62.583.gdac8683d-a
 - Spicetify version 2.5.0
 - Dribbblish base

**Comment by morpheusthewhite** [comment]
Are you using the `v2` branch?

**Comment by lolpowerluke** [comment]
once I apply the theme, it becomes like this
![image](https://user-images.githubusercontent.com/47672899/125168494-1b134300-e1a6-11eb-9a8a-a99dd0785bb6.png)
I used the tutorial from this video btw
https://www.youtube.com/watch?v=rRhratE0KNk&t

**Comment by Tekunalogy** [comment]
I have the same issue as above, but I get this error `error Cannot find symbol for Custom app React symbols`

``` powershell
PS C:\WINDOWS\system32> spicetify apply
spicetify v2.4.0
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Overwriting custom assets:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
Transferring extensions:
OK
success Spotify is spiced up!
```

**Comment by lolpowerluke** [comment]
yes, forgot to add that part, exactly the same for me

**Comment by BritishBenji** [comment]
Same issue here, tried various themes and it's all just one block of color.
- Windows 10
- Spicetifty v 2.5.0
- Latest version of Spotify

**Comment by GRcrafter** [comment]
Same problem here:

- Latest Spotify version (not sure about the spicetify version, but I think its the latest one)
- Windows 10
- Theme: Dribbblish gruvbox
- I also followed this video: https://www.youtube.com/watch?v=rRhratE0KNk
- Error code: Cannot find symbol for Custom app React symbols
![image](https://user-images.githubusercontent.com/82709728/125305785-51cc9300-e337-11eb-8690-8942295ccc07.png)

**Comment by jiznon** [comment]
Same issue here. Downgrading to 1.1.62.583 and is working for the meantime.

**Comment by GRcrafter** [comment]
Update:
I found this guide in No Text To Speech's discord server (https://discord.gg/ntts):
you could always try uninstalling spotify, using my script in #💬︱techy-talk then do your config from there :person_shrugging:
or just do this:
-uninstall spotify
-delete both spicetify folders in your user folder (.spicetify, and spicetify-cli)
-delete your spotify folder in %appdata%local
-delete everything in %temp%

-install this ver of spotify 
https://cdn.discordapp.com/attachments/858569222816530492/863503385486688256/spotify-1-1-62-583.exe
-then create a folder in %appdata%local/spotify
call it User

-and set the user group permissions so that trusted installer and system have permissions blocked

-open powershell and paste this into it Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression

-type spicetify and hit enter once

-run this spicetify backup apply enable-devtool

-close spotify


Now you can do your themes and extensions
here is an example:
spicetify config extensions dribbblish.js
spicetify config extensions fullAppDisplay.js
spicetify config current_theme Dribbblish
spicetify config color_scheme beach-sunset
spicetify config inject_css 1 replace_colors 1 overwrite_assets 1
spicetify config custom_apps lyrics-plus
spicetify apply


Make sure you have put your theme (from the v2 branch https://github.com/morpheusthewhite/spicetify-themes/tree/v2) into the theme folder in %user%.spicetify/themes, DO THIS BEFORE THE COMMANDS. If you are using a theme such as dribbblish, that has a custom .js, simply move it from themes folder to extensions folder. Or use the built in .psi install, however simply moving the .js is easiest.

if you would like no controls in the top right of your screen, download and use this exe https://discord.com/channels/820745488231301210/858569222816530492/863459041568882708, either replace your old spotify shortcut by searching for it, right clicking, clicking properties, and overwriting its target to wherever you have this exe saved. Or just run this exe whenever you want it.

**Comment by morpheusthewhite** [comment]
Refer to related issue on `spicetify-cli`:

https://github.com/khanhas/spicetify-cli/issues/845

**Comment by ChristianVaughn** [comment]
As of today there has been an update that fixes most of the hooks. After updating spicetify I tried using dribblish and it now looks like this. Seems as if the js file isn't properly being run or something like that since all the color changes are there, but not some of the UI changes like the sidebar.
![image](https://user-images.githubusercontent.com/4643028/129791567-7837f53d-a511-4849-a106-4fe1d3f71b0c.png)

**Comment by Hu1buerger** [comment]
I tried the new version and it seems to work. Will close this issue if not veto is called.

**Comment by minhduc0711** [comment]
One small issue: most of my left sidebar icons are blurry, and one non-blurry icon is horizontally stretched (the smiling frog one)
![image](https://user-images.githubusercontent.com/34294427/133957871-fd09dd9e-61d3-4c03-8520-370a5a3212a4.png)
