### ISSUE TITLE
[ShadowCustom] How do I reduce the heights of the player box?

### ISSUE THREAD

**Issue by Pistrie** [morpheusthewhite/spicetify-themes#46]
https://i.imgur.com/jSYZT3d.png
As you can see there is a lot of space between the bottom of the window and the media controls. How do I reduce this?

Not really an issue, but more of a request

**Comment by morpheusthewhite** [comment]
Since the media controls are centered in the player bar one obvious solution is to reduce the height of the bar (which you can find at the top of the `user.css`). 

In general to test small (or in general any) modifications you can enable dev-tools by 
```
spicetify backup apply enable-devtool
```
and then right click on the application and inspect the page
