### ISSUE TITLE
Spicetify install renders Spotify completely white

### ISSUE THREAD

**Issue by iBuffering** [morpheusthewhite/spicetify-themes#476]
**Describe the bug**
Spicetify makes my spotify completely white

**To Reproduce**
1. Follow installation instruction
2. Run  `spicetify` in PowerShell
3. Run `spicetify backup apply enable-devtool`

**Screenshots**
![image](https://user-images.githubusercontent.com/12660678/126866863-c2ce1614-85ae-486e-92e2-3868875798b0.png)
![image](https://user-images.githubusercontent.com/12660678/126867098-ffff6ae2-b01a-46f7-b055-a8a9b9134fb2.png)

**Logs**

```console
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics**
 - OS: Windows
 - Spotify version 1.1.64.561.g71bd09eb-a
 - Spicetify version 2.5.0

**Comment by ps13g** [comment]
In order to actually fix this issue you will have to downgrade to an older version of spotify. All I know as of right now is that devs are trying to work on a fix but an update can take longer to push out. I would suggest you watch this video in order to know how to actually downgrade [(https://www.youtube.com/watch?v=lPUFzDes_Eg&ab_channel=NoTextToSpeech )].

**Comment by iBuffering** [comment]
Thank you so much, I was losing my mind thinking I was doing something wrong. I thought the issues with the latest version of spotify were only tied to a specific theme. Will downgrade and close the issue if it's working.

**Comment by morpheusthewhite** [comment]
Look at the pinned issue

**Comment by iBuffering** [comment]
@ps13g I followed the tutorial but I can't seem to get it working, all I get is a window with a green background
